### ISSUE TITLE
How can lightblue json language be improved for multi-level arrays?

### ISSUE THREAD

**Issue by paterczm** [lightblue-platform/lightblue-core#315] opened 2015-02-12 16:10 UTC
Manipulating data in an array inside array is problematic, the amount of nesting makes it hard to read. Example:

```json 
  "update": [      
        {    
            "$foreach": {    
                "$update": {    
                    "$foreach": {    
                        "$update": {    
                            "$set": {    
                                "statusCode": "inactive"    
                            }    
                        },    
                        "termsVerbiageTranslation": {    
                            "field": "localeCode",    
                            "op": "=",    
                            "rvalue": "en"    
                        }    
                    }    
                },    
                "termsVerbiage": {    
                    "field": "uid",    
                    "op": "=",    
                    "rvalue": "a44dec05-d1c5-413e-a8ff-5bb56feab411"    
                }    
            }    
        }    
  ]
```
 
For comparison, think about sql update statement over 2 tables.
```sql
UPDATE termsVerbiageTranslation t SET statusCode='inactive' WHERE 
t.localeCode='en' and t.termsVerbiageId='a44dec05-d1c5-413e-a8ff-5bb56feab411';  
```

The more array levels you have, the less readable the queries become.

**Comment by jewzaam** [comment] 2015-02-20 19:33
Is this a duplicate of #236?

**Comment by bserdar** [comment] 2015-02-20 19:34
it is.

**Comment by jewzaam** [comment] 2015-02-20 21:11
Closing as duplicate of #236

**Closed by jewzaam** 2015-02-20 21:11 UTC
Labels: enhancement, will not fix
