### ISSUE TITLE
AbstractMetadataConfiguration, and in general, all configuration classes need to be refactored

### ISSUE THREAD

**Issue by bserdar** [lightblue-platform/lightblue-core#172] opened 2014-10-16 19:20 UTC
This is a chicken and egg problem. AbstractMetadataConfiguration is reading back end parsers, property parsers from a configuration file, instantiating them, and registering them to the Extensions instance. However, implementations of those are build and run-time dependencies, and ultimately, the front end knows what's there and what's not. So, instead of reading then from a configuration, we should:
 1) Have the top-level application (rest-metada and rest-crud apps) construct Extensions instance with hard-coded extensions. The top-level application doesn't have to know what those indiviual extensions are. Every subsystem can provide some sort of a callback to register themselves. For instance, call a register(Extensions) API on rdbms controller module, and it registers all extensions defined in that module. Some sort of subsystem metadata class to do this is useful, something line MongoControllerInfo and RDBMSControllerInfo. BackEnd configuration can provide it.
 2) Pass that extensions to MetadataConfiguration, and anybody who needs it. This doesn't only relate to the metadata configiration. A lot of cofiguraton classes are shared between crud and metadata.

**Comment by jewzaam** [comment] 2015-04-27 14:34
See https://github.com/lightblue-platform/lightblue-rest/issues/21

**Comment by jewzaam** [comment] 2015-04-27 14:35
Duplicate of https://github.com/lightblue-platform/lightblue-core/issues/285

**Closed by jewzaam** 2015-04-27 14:35 UTC
Labels: enhancement, ready
